name: Create Release

on:
    push:
        branches:
            - main
        paths:
            - 'manifest.json'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Ensures the full history is fetched

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.8.0'

            - name: Install Dependencies
              run: npm install

            - name: Build the Project
              run: npm run build:action

            - name: Get the version
              id: get_version
              run: |
                  VERSION=$(npm run version:show | tail -n 1)
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
              shell: bash

            - name: Get previous release tag
              id: get_previous_release
              run: |
                  echo "Fetching previous release tag..."
                  previous_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
                  if [ -z "$previous_tag" ]; then
                    echo "No previous tag found, using initial commit."
                    previous_tag=$(git rev-list --max-parents=0 HEAD)
                  fi
                  echo "Previous tag: $previous_tag"
                  echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV
              shell: bash

            - name: Generate release notes
              id: generate_notes
              run: |
                  echo "Generating release notes from ${{ env.PREVIOUS_TAG }} to HEAD..."
                  repo_url=$(git config --get remote.origin.url)
                  notes=$(git log ${{ env.PREVIOUS_TAG }}..HEAD --pretty=format:"- [\`%h\`]($repo_url/commit/%H): %s%n")
                  echo "Release notes:"
                  echo "$notes"
                  echo "NOTES<<EOF" >> $GITHUB_ENV
                  echo "### Changes in this release" >> $GITHUB_ENV
                  echo "$notes" >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
              shell: bash

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.VERSION }}
                  release_name: Release ${{ env.VERSION }}
                  body: ${{ env.NOTES }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset main.js
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/main.js
                  asset_name: main.js
                  asset_content_type: application/javascript

            - name: Upload Release Asset styles.css
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/styles.css
                  asset_name: styles.css
                  asset_content_type: text/css

            - name: Upload Release Asset manifest.json
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./manifest.json
                  asset_name: manifest.json
                  asset_content_type: application/json
