name: Create Release

on:
    push:
        branches:
            - main
        paths:
            - "manifest.json"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Get the version
              id: get_version
              run: echo "::set-output name=VERSION::$(jq -r .version manifest.json)"
              shell: bash

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.get_version.outputs.VERSION }}
                  release_name: Release ${{ steps.get_version.outputs.VERSION }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset main.js
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/main.js
                  asset_name: main.js
                  asset_content_type: application/javascript

            - name: Upload Release Asset styles.css
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/styles.css
                  asset_name: styles.css
                  asset_content_type: text/css

            - name: Upload Release Asset manifest.json
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./build/manifest.json
                  asset_name: manifest.json
                  asset_content_type: application/json
